# Generated by Django 4.1.3 on 2022-12-19 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1)),
                ('especie', models.CharField(max_length=50)),
                ('fCreacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SeguroMedico',
            fields=[
                ('idPlan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=10)),
                ('dosis', models.FloatField()),
                ('unidadDosis', models.CharField(choices=[('g', 'Gramo'), ('mg', 'Miligramo'), ('ml', 'Mililitro')], max_length=2)),
                ('fCreacion', models.DateField(default=django.utils.timezone.now)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='playground.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='playground.seguromedico'),
        ),
    ]
